default: &default
  adapter: postgresql
  encoding: utf8
  pool: 5
  host: localhost
  username: pguser
  password: root

development:
  <<: *default
  database: successclub_pg

test:
  <<: *default
  database: succsessclub_pg
  username: pguser

production:
  <<: *default
  database: <%= ENV['CLUB_DATABASE_NAME']%>
  username: <%= ENV['CLUB_DATABASE_USER']%>
  password: <%= ENV['CLUB_DATABASE_PASSWORD']%>
